env:
  - GO111MODULE=on
  - CGO_ENABLED=0

gomod:
  proxy: true

before:
  hooks:
    - go mod download
    #- go generate ./...

builds:
  - id: linux/amd64
    binary: identity-manager_{{.Target}}
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser -linkmode internal -extldflags -static
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    no_unique_dist_dir: true
  - id: linux/arm64
    binary: identity-manager_{{.Target}}
    goos:
      - linux
    goarch:
      - arm64
    goarm:
      - "7"
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser -linkmode internal -extldflags -static
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    no_unique_dist_dir: true
  - id: darwin/arm64
    binary: identity-manager_{{.Target}}
    goos:
      - darwin
    goarch:
      - arm64
    goarm:
      - "7"
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser -linkmode internal -extldflags -static
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    no_unique_dist_dir: true

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
