# permissions for end users to view workloadidentities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workloadidentity-viewer-role
rules:
- apiGroups:
  - identity-manager.io
  resources:
  - workloadidentities
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - identity-manager.io
  resources:
  - workloadidentities/status
  verbs:
  - get
