apiVersion: identity-manager.io/v1alpha1
kind: WorkloadIdentity
metadata:
  namespace: dev
  name: demo-identity
spec:
  aws:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Federated": "arn:aws:iam::123458189203:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/3B9D12F2B3C93CF2AFA0B1FC02996E2A"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
              "StringEquals": {
                "oidc.eks.us-east-1.amazonaws.com/id/3B9D12F2B3C93CF2AFA0B1FC02996E2A:sub": "system:serviceaccount:dev:demo"
              }
            }
          }
        ]
      }
    inlinePolicies:
      s3-listBucket-0: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "s3:GetObject"
              ],
              "Resource": [
                "*"
              ]
            }
          ]
        }
    maxSessionDuration: 3600
    path: /
    pods:
      - matchLabels:
          app.kubernetes.io/name: demo-identity
          app.kubernetes.io/version: v1
    serviceAccounts:
      - action: Create
        name: demo
        namespace: dev
  description: 'identity for S3 app'
  name: demo-identity
  provider: AWS
