apiVersion: identity-manager.io/v1alpha1
kind: WorkloadIdentity
metadata:
  namespace: demo
  name: demo-identity
spec:
  aws:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Federated": "arn:aws:iam::${ACCOUNT_ID}:oidc-provider/${OIDC_PROVIDER}"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
              "StringEquals": {
                "${OIDC_PROVIDER}:sub": "system:serviceaccount:demo:sa-demo"
              }
            }
          }
        ]
      }
    inlinePolicies:
      ec2-describe-0: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "ec2:Describe*"
              ],
              "Resource": [
                "*"
              ]
            }
          ]
        }
    maxSessionDuration: 3600
    path: /
    pods:
      - matchLabels:
          app.kubernetes.io/name: demo
          app.kubernetes.io/version: v1
    serviceAccounts:
      - action: Create
        name: sa-demo
        namespace: demo
  description: 'identity for demoworkload'
  name: demo-identity
  provider: AWS
