{{- if and .Values.rbac.enabled .Values.rbac.namespaced -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "identity-manager.fullname" . }}
  labels:
    {{- include "identity-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "identity-manager.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "identity-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
