{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "identity-manager.serviceAccountName" . }}
  labels:
    {{- include "identity-manager.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.provider.aws.enabled }}
    eks.amazonaws.com/role-arn: {{ .Values.provider.aws.arn }}
  {{- end }}
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
