name: PR

on:
  pull_request:
    branches:
      - main
      - "[0-9]+.[0-9]+.[0-9]+-*"
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      # note: golangci-lint caches go mod
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49.0
      - name: Unit test
        run: make test
